services:

  # Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: securebank-oracle
    environment:
      ORACLE_PWD: SecureBank#123
    ports:
      - "1522:1521"
  prometheus:
    image: prom/prometheus:latest
    container_name: securebank-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - securebank-pipeline_securebank-network

  grafana:
    image: grafana/grafana:latest
    container_name: securebank-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - securebank-pipeline_securebank-network

networks:
  securebank-pipeline_securebank-network:
    external: true

volumes:
  oracle-data:
  jenkins-data:
  document-storage:
  grafana_data:
