apiVersion: v1
kind: Secret
metadata:
  name: securebank-secrets
  namespace: securebank
type: Opaque
stringData:
  oracle-password: SecureBank#123
  jwt-secret: SecureBankJWTSecret2024
  dockerhub-username: dhivyadev
