spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://config-server:8071/"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
