apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: dhivyadev/securebank-pipeline-auth-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        envFrom:
        - configMapRef:
            name: securebank-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: securebank
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080
    targetPort: 8080
